module.exports = {
  async up(queryInterface) {
    const skills = [
      { id: 1, name: 'Python' },
      { id: 2, name: 'Java' },
      { id: 3, name: 'C++' },
      { id: 4, name: 'JavaScript' },
      { id: 5, name: 'HTML' },
      { id: 6, name: 'CSS' },
      { id: 7, name: 'TypeScript' },
      { id: 8, name: 'React' },
      { id: 9, name: 'Angular' },
      { id: 10, name: 'Vue.js' },
      { id: 11, name: 'Node.js' },
      { id: 12, name: 'Django' },
      { id: 13, name: 'Flask' },
      { id: 14, name: 'Ruby on Rails' },
      { id: 15, name: 'SQL' },
      { id: 16, name: 'PostgreSQL' },
      { id: 17, name: 'MySQL' },
      { id: 18, name: 'MongoDB' },
      { id: 19, name: 'Git' },
      { id: 20, name: 'GitHub' },
      { id: 21, name: 'GitLab' },
      { id: 22, name: 'AWS' },
      { id: 23, name: 'Azure' },
      { id: 24, name: 'Google Cloud' },
      { id: 25, name: 'Docker' },
      { id: 26, name: 'Kubernetes' },
      { id: 27, name: 'Jenkins' },
      { id: 28, name: 'Travis CI' },
      { id: 29, name: 'CircleCI' },
      { id: 30, name: 'RESTful APIs' },
      { id: 31, name: 'GraphQL' },
      { id: 32, name: 'TensorFlow' },
      { id: 33, name: 'PyTorch' },
      { id: 34, name: 'Scikit-Learn' },
      { id: 35, name: 'Pandas' },
      { id: 36, name: 'NumPy' },
      { id: 37, name: 'R' },
      { id: 38, name: 'Matplotlib' },
      { id: 39, name: 'D3.js' },
      { id: 40, name: 'Tableau' },
      { id: 41, name: 'Hadoop' },
      { id: 42, name: 'Spark' },
      { id: 43, name: 'Swift' },
      { id: 44, name: 'Kotlin' },
      { id: 45, name: 'Flutter' },
      { id: 46, name: 'React Native' },
      { id: 47, name: 'Unity' },
      { id: 48, name: 'Unreal Engine' },
      { id: 49, name: 'Linux' },
      { id: 50, name: 'Windows' },
      { id: 51, name: 'macOS' },
      { id: 52, name: 'Bash' },
      { id: 53, name: 'PowerShell' },
      { id: 54, name: 'VMware' },
      { id: 55, name: 'VirtualBox' },
      { id: 56, name: 'Blockchain' },
      { id: 57, name: 'AR/VR Development' },
      { id: 58, name: 'Cybersecurity' },
      { id: 59, name: 'Penetration Testing' },
      { id: 60, name: 'Encryption' },
      { id: 61, name: 'Network Configuration' },
      { id: 62, name: 'Network Management' },
      { id: 63, name: 'Mobile Development' },
      { id: 64, name: 'Embedded Systems' },
      { id: 65, name: 'IoT' },
      { id: 66, name: 'Robotics' },
      { id: 67, name: 'Hardware Prototyping' },
      { id: 68, name: 'Computer Vision' },
      { id: 69, name: 'Cloud Security' },
      { id: 70, name: 'API Integration' },
      { id: 71, name: 'Serverless Architecture' },
      { id: 72, name: 'Agile Methodologies' },
      { id: 73, name: 'Scrum' },
      { id: 74, name: 'Kanban' },
      { id: 75, name: 'JIRA' },
      { id: 76, name: 'Trello' },
      { id: 77, name: 'Power BI' },
      { id: 78, name: 'UX/UI Design' },
      { id: 79, name: 'Software Testing' },
      { id: 80, name: 'Unit Testing' },
      { id: 81, name: 'Integration Testing' },
      { id: 82, name: 'Test Automation' },
      { id: 83, name: 'Selenium' },
      { id: 84, name: 'JUnit' },
      { id: 85, name: 'Performance Tuning' },
      { id: 86, name: 'Optimization' },
      { id: 87, name: 'Software Architecture' },
      { id: 88, name: 'Middleware' },
      { id: 89, name: 'ETL Processes' },
      { id: 90, name: 'Configuration Management' },
      { id: 91, name: 'Ansible' },
      { id: 92, name: 'Puppet' },
      { id: 93, name: 'Chef' },
      { id: 94, name: 'Load Balancing' },
      { id: 95, name: 'Network Security' },
      { id: 96, name: 'Infrastructure as Code' },
      { id: 97, name: 'Terraform' },
      { id: 98, name: 'CloudFormation' },
      { id: 99, name: 'Big Data' },
      { id: 100, name: 'Artificial Intelligence' },
    ];

    return await queryInterface.bulkInsert('Skills', skills, {});
  },

  async down(queryInterface) {
    return await queryInterface.bulkDelete('Skills', null, {});
  },
};
